### interview 代理
GET {{url}}/proxy/jdk?msg=taylor
Accept: */*
Cache-Control: no-cache

### interview - 获取单例
GET {{url}}/concurrent/singleton
Accept: */*
Cache-Control: no-cache

### interview - forkJoinTask
GET {{url}}/concurrent/forkJoinTask/1/54
Accept: */*
Cache-Control: no-cache

######## --- review --- ########

# 1 充值 2 消费
GET {{url}}/concurrent/AtomicStampedReference/2
Accept: */*
Cache-Control: no-cache

### Parallel 并行
GET {{url}}/concurrent/completableFuture/3
Accept: */*
Cache-Control: no-cache

### 策略模式
GET {{url}}/order/handle/2
Accept: */*
Cache-Control: no-cache

###

######## --- time - 并发 --- ########
GET {{url}}/avoidDeadlock/transfer?from=A&to=B&money=10
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/cl/handler
Accept: */*
Cache-Control: no-cache

### 事务传播模式
GET {{url}}/transactional/required
Accept: */*
Cache-Control: no-cache

### @Select 操作数据库
GET {{url}}/anndao/getList
Accept: */*
Cache-Control: no-cache

###