server:
  port: 9090

#关闭健康监测
endpoints:
  health:
     enabled: false

spring:
  application.name: rabbitmq
  profiles.active: rabbitmq

  rabbitmq:
    host: 39.106.118.71
    # port 对应的是 5672 不是web 管理的 15672 ,增加完角色后 权限的赋予
    port: 5672
    username: chengyufei
    password: chengyufei
    publisher-confirms: true
    listener:
      simple:
      #手动确认
        acknowledge-mode: MANUAL
      # listener 最少启用2线程
        concurrency: 2
        # 每个线程每次消费3条消息
        prefetch: 3


#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
spring.aop.proxy-target-class: true
---
spring:
  profiles: rabbitmq







