server:
  port: 9090
  maxPostSize: 0
spring:
  application.name: newredis
  profiles.active: dev
  redis:
    host: 39.106.118.71
    password: 68A61C323A3452544C4AEF6296D8BD95A
    #      pool:
    #        max-active: 300
    #        max-idle: 200
    #        max-wait: 10000
    #        min-idle: 20
    port: 6380




#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
spring.aop.proxy-target-class: true
#JACKSON
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL
  time-zone: GMT+8

---
spring.profiles: newredis
#spring.profiles.include: dao-dev






