server:
  port: 7070

spring:
  application.name: interview
  profiles.active: interview
app.id: SampleApp
apollo.meta: http://211.159.175.105:8080
#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
#spring.aop.proxy-target-class: true
---
spring:
  profiles:
    include: interview







