###
GET {{url}}/sharing/insert
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
"username":"读写分离：写_3",
"pwd":"pwd"
}

###
GET {{url}}/sharing/selectById/1
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/sharing/insertRecord
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "content":"G"
}

###
GET {{url}}/sharing/getRecordList?name=%25_14%25
Accept: */*
Cache-Control: no-cache

###
GET {{url}}/sharing/selectRecordById/370519284457144321
Accept: */*
Cache-Control: no-cache

###