#数据库连接   多数据源 配置
hikari:
  datasource:
    primary:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbcUrl: "jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false"
      autoCommit: true
      #连接超时5s
      connectionTimeout:  5000
      #空闲超时时间（10分钟）
      idleTimeout:  600000
      #最大存活时间 （最好设置）默认30分钟
      maxLifetime: 1800000
      #最大连接池大小  = ((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 10
      minimumIdle: 5

#    secondary:
#      driverClassName: com.mysql.jdbc.Driver
#      username: root
#      password: daishumovie
#      jdbcUrl: "jdbc:mysql://192.168.1.200:3306/worthyVideoAdmin?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false"
#      autoCommit: true
#      #连接超时5s
#      connectionTimeout:  5000
#      #空闲超时时间（10分钟）
#      idleTimeout:  600000
#      #最大存活时间 （最好设置）默认30分钟
#      maxLifetime: 1800000
#      #最大连接池大小
#      maximumPoolSize: 10
#      minimumIdle: 5
#    threeary:
#      driverClassName: com.mysql.jdbc.Driver
#      username: root
#      password: daishumovie
#      jdbcUrl: "jdbc:mysql://192.168.1.200:3306/db_video_crawler?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false"
#      autoCommit: true
#      #连接超时5s
#      connectionTimeout:  5000
#      #空闲超时时间（10分钟）
#      idleTimeout:  600000
#      #最大存活时间 （最好设置）默认30分钟
#      maxLifetime: 1800000
#      #最大连接池大小
#      maximumPoolSize: 10
#      minimumIdle: 5
#



#redis连接
spring:
  redis:
    host: 39.106.118.71
    password: 68A61C323A3452544C4AEF6296D8BD95A61B8C8FA8AC0C07BEA1D176847909C6
    pool:
      max-active: 300
      max-idle: 200
      max-wait: 10000
      min-idle: 20
    port: 6380


#mongodb:
mongodb:
  primary:
    host: 39.106.118.71
    port: 27017
    database: cyfdb
    uri: mongodb://39.106.118.71:27017/cyfdb
  second:
     host: 39.106.118.71
     port: 27017
     database: local
     uri: mongodb://39.106.118.71:27017/cyfdb_second



#
#ali.oss.endpoint: "http://oss-cn-shanghai.aliyuncs.com"
#
##格式 mongodb://{user}:{pwd}@{host}:{port}/{database}
##spring.data.mongodb.uri: mongodb://root:1234@192.168.1.200:27017/admin

