### api Hystrix 注解模式
GET {{url}}/command/user?username=hystrix&orderName=order
Accept: */*
Cache-Control: no-cache

### api Hystrix
GET {{url}}/command/get
Accept: */*
Cache-Control: no-cache

### api Guava-cache
GET {{url}}/cache/get?key=6
Accept: */*
Cache-Control: no-cache

### api Guava-EventBus
GET {{url}}/event/post
Accept: */*
Cache-Control: no-cache


### api 事务
GET {{url}}/transaction/test
Accept: */*
Cache-Control: no-cache

### api @async 自调用
GET {{url}}/async/handle
Accept: */*
Cache-Control: no-cache

### interview 代理
GET {{url}}/proxy/jdk?msg=taylor
Accept: */*
Cache-Control: no-cache

### interview - 获取单例
GET {{url}}/concurrent/singleton
Accept: */*
Cache-Control: no-cache

### batch 10w 130s
GET {{url}}/batch/execute
Accept: */*
Cache-Control: no-cache

### batch 10w 75s
GET {{url}}/batch/commExecute
Accept: */*
Cache-Control: no-cache

### redis
GET {{url}}/newredis/user/getUser/2/Tay/Tay
Accept: */*
Cache-Control: no-cache

### redis
GET {{url}}/newredis/user/kerrs
Accept: */*
Cache-Control: no-cache

### redis - delay
GET {{url}}/newredis/user/delay
Accept: */*
Cache-Control: no-cache

### mq - common
GET {{url}}/send
Accept: */*
Cache-Control: no-cache

### mq 延时
GET {{url}}/sendDelay
Accept: */*
Cache-Control: no-cache
###