### api Hystrix 注解模式
GET {{url}}/command/user?username=hystrix&orderName=order
Accept: */*
Cache-Control: no-cache

### api Hystrix
GET {{url}}/command/get
Accept: */*
Cache-Control: no-cache

### api Guava-cache
GET {{url}}/cache/get?key=6
Accept: */*
Cache-Control: no-cache

### api Guava-EventBus
GET {{url}}/event/post
Accept: */*
Cache-Control: no-cache

### interview 代理
GET {{url}}/proxy/jdk?msg=taylor
Accept: */*
Cache-Control: no-cache

### batch
GET {{url}}/batch/execute
Accept: */*
Cache-Control: no-cache

###