### api user 数据加密
#POST {{url}}/user/byName?name=yu
GET {{url}}/user/byId?id=1
#GET {{url}}/user/select?username=if&uid=2
Accept: */*
Cache-Control: no-cache


### api Hystrix 注解模式
GET {{url}}/command/user?username=hystrix&orderName=order
Accept: */*
Cache-Control: no-cache

### api Hystrix
GET {{url}}/command/get
Accept: */*
Cache-Control: no-cache

### api Guava-cache
GET {{url}}/cache/get?key=6
Accept: */*
Cache-Control: no-cache

### api Guava-EventBus
GET {{url}}/event/post
Accept: */*
Cache-Control: no-cache

### api 事务
GET {{url}}/transaction/test
Accept: */*
Cache-Control: no-cache

### api @async 自调用
GET {{url}}/async/handle
Accept: */*
Cache-Control: no-cache

### api FutureTask commonHandle   futureHandle
GET {{url}}/future/futureHandle
Accept: */*
Cache-Control: no-cache


### batch 10w 130s
GET {{url}}/batch/execute
Accept: */*
Cache-Control: no-cache

### batch 10w 75s
GET {{url}}/batch/commExecute
Accept: */*
Cache-Control: no-cache

### redis
GET {{url}}/newredis/user/getUser/2/Tay/Tay
Accept: */*
Cache-Control: no-cache

### redis
GET {{url}}/newredis/user/kerrs
Accept: */*
Cache-Control: no-cache

### redis - delay
GET {{url}}/newredis/user/delay
Accept: */*
Cache-Control: no-cache

### mq - common
GET {{url}}/send
Accept: */*
Cache-Control: no-cache

### mq 延时
GET {{url}}/sendDelay
Accept: */*
Cache-Control: no-cache

### mq 异常消息存入死信
GET {{url}}/sendGeneral
Accept: */*
Cache-Control: no-cache

### pay
GET {{url}}/pay/wxUnifyOrder
Accept: */*
Cache-Control: no-cache

### jodd
GET {{url}}/jodd/faceAudit?url=http://xclub.oss-cn-shanghai.aliyuncs.com/3000/image/client/2018/8/16/218B0542F31A44FA95357E842EB93C70.jpg
Accept: */*
Cache-Control: no-cache

###