server:
  port: 8090
  maxPostSize: 0
spring:
  application.name: api
  profiles.active: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  data:
    web:
      pageable:

      # 分页大小 默认为 20
        default-page-size: 2
        #当前页参数名 默认为 page
        page-parameter: pageNumber
#        当前页参数名 默认为 size
        size-parameter: pageSize

        # 字段排序参数名 默认为 sort
      sort:
        sort-parameter: orderBy

#springboot-admin-monitor
  boot:
    admin:
      client:
        url: http://127.0.0.1:6060

# 指定sentinel 面板地址 ,此方式没生效，通过启动添加VM Option: -Dcsp.sentinel.dashboard.server=39.106.118.71:8333 生效
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 39.106.118.71:8333
async:
     pool:
        #核心线程数
        corePoolSize: 5
        #最大线程数
        maxPoolSize: 30
        #线程池维护线程所允许的空闲时间
        keepAliveSeconds: 60
        #队列长度
        queueCapacity: 1000

#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
# 或者 @EnableAspectJAutoProxy(proxyTargetClass = true)
#spring.aop.proxy-target-class: true

#JACKSON
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL
  time-zone: GMT+8
#Prometheus
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}


---
spring.profiles: dev
spring.profiles.include: dao-dev

---
spring.profiles: prod
spring.profiles.include: dao-prod
#---
#spring.profiles: test
#spring.profiles.include: dao-test,wechat-test,search-test
#
#ali.oss.endpoint: "oss-cn-shanghai.aliyuncs.com"
#app:
#  apiPrefix: http://api.daishumovie.com
#  sharePrefix: http://m.movie.com
#  autoplayUsingWifi: 1
#  mustBindMobile: 1
#aliyun:
#  sms-is-send: true






