server:
  port: 9090
  context-path: /
  maxPostSize: 0
spring:
  application.name: search
  profiles.active: dev



#而当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现
spring.aop.proxy-target-class: true

#JACKSON
spring.jackson:
  date-format: "yyyy-MM-dd HH:mm:ss"
  default-property-inclusion: NON_NULL
  time-zone: GMT+8


spring.elasticsearch.jest:
  connection-timeout: 3000 # Connection timeout in milliseconds.
  multi-threaded: true # Enable connection requests from multiple execution threads.
  proxy.host:  # Proxy host the HTTP client should use.
  proxy.port:  # Proxy port the HTTP client should use.
  read-timeout: 3000 # Read timeout in milliseconds.
  uris: http://39.106.118.71:9200,http://39.106.118.71:9201
  username: elastic # Login user.
  password: chengyufei # Login password.



---
spring.profiles: dev
#spring.profiles.include: dao-dev






